services:
  - type: web
    name: pscmaster-api
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 10000
